language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
  
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly