name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: PHPUnit unit tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Check PHP Version
        run: php -v

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test
